 export const randomThings = [
    "A book",
    "A pen",
    "A pencil",
    "A notebook",
    "A laptop",
    "A phone",
    "A tablet",
    "A desk",
    "A chair",
    "A lamp",
    "A plant",
    "A picture frame",
    "A vase",
    "A clock",
    "A calendar",
    "A whiteboard",
    "A stapler",
    "A tape dispenser",
    "A scissors",
    "A ruler",
    "A pencil sharpener",
    "A paper clip holder",
    "A paper punch",
    "A trash can",
    "A recycling bin",
    "A grocery list",
    "A schedule",
    "A planner",
    "A passport",
    "A driver's license",
    "A credit card",
    "A debit card",
    "A cash",
    "A checkbook",
    "A wallet",
    "A keychain",
    "A keys",
    "A sunglasses",
    "A hat",
    "A scarf",
    "A coat",
    "A jacket",
    "A umbrella",
    "A gloves",
    "A socks",
    "A shoes",
    "A boots",
    "A sandals",
    "A dress",
    "A skirt",
    "A pants",
    "A shorts",
    "A t-shirt",
    "A shirt",
    "A blouse",
    "A sweater",
    "A sweatshirt",
    "A hoodie",
    "A makeup",
    "A perfume",
    "A lotion",
    "A hair brush",
    "A hair ties",
    "A hair clips",
    "A toothbrush",
    "A toothpaste",
    "A mouthwash",
    "A floss",
    "A band-aid",
    "A pain reliever",
    "A cold medicine",
    "A allergy medicine",
    "A first aid kit",
    "A water bottle",
    "A snack",
    "A lunch box",
    "A bag",
    "A backpack",
    "A suitcase",
    "A luggage"
  ];

